name: AquaCore-Food
version: '1.1-SNAPSHOT'
main: com.aquacore.food.AquaCoreFood
api-version: '1.21'
softdepend: [PlaceholderAPI]
authors: [Jume,Antigravity]
description: Custom food and saturation mechanics.

commands:
  aquafood:
    description: Main command for AquaCore-Food
    usage: /aquafood help
    permission: aquafood.use
    aliases: [afood]

permissions:
  aquafood.use:
    description: Allows use of basic commands
    default: true
  aquafood.admin:
    description: Allows use of admin commands (set, add, reload)
    default: op
